### ISSUE TITLE
issue with Age Verify w/ Email Capture app on my shopify store

### ISSUE THREAD

**Issue by dannykatz** [baumant/age-verification-with-email-capture#19]
After entering date of birth app is asking for more verification. How to remove and only ask visitors one time

**Comment by baumant** [comment]
This will only happen when one IP address has been submitting the age verification form multiple times in a short period of time, it's a security feature of Shopify forms (https://shopify.dev/themes/trust-security/captcha). So if you were testing submissions multiple times you might see a captcha pop up, it resets after a time (24 hours or so). Everyone else seeing the form won't have that extra verification pop up, only the IP that has been submitting the form.
