### ISSUE TITLE
Dont know what's wrong, theme issue?

### ISSUE THREAD

**Issue by gaslabs** [baumant/age-verification-with-email-capture#2]
https://cdn.shopify.com/s/files/1/0301/0897/5239/files/2020-01-10.png?v=1578634614

**Comment by baumant** [comment]
certain themes will show this error if they don't support theme translations. Please reach out to age.verify.contact@gmail.com and I'd be happy to help fix the error message for your theme.

**Comment by baumant** [comment]
This has been fixed in the latest update, reinstalling the app will pull the latest code with fallbacks for themes without translations. Still happy to help fix older versions of the app, just reach out!
