### ISSUE TITLE
Email Capture Show's Error in Typefield

### ISSUE THREAD

**Issue by MaluxProduction** [baumant/age-verification-with-email-capture#3]
Above the button of the Email Capture where the typefield is placed, it show's an error something like "translation missing: de.ge..."
I can't read further. Can you solve this Bug?

**Comment by fischersd** [comment]
+1 Also having that here "translation missing:  en.genera...."  (so, not language specific, seemingly).
Disabled the e-mail capture feature until this is fixed.

**Comment by eduardo0820** [comment]
Also having that here "translation missing: en.genera...." Can you solve this Bug or any suggestions to fix it myself?

**Comment by SolisticCBD** [comment]
Same problem here.
![2020-10-28](https://user-images.githubusercontent.com/73604167/97464274-b1505300-190e-11eb-975f-65ed1063be1d.png)

**Comment by baumant** [comment]
Same as #2 , certain themes will show this error if they don't support theme translations. Please reach out to age.verify.contact@gmail.com and I'd be happy to help fix the error message for your theme.

**Comment by baumant** [comment]
This has been fixed in the latest update, reinstalling the app will pull the latest code with fallbacks for themes without translations. Still happy to help fix older versions of the app, just reach out!
